// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://bxxmtptvxkgpeqmwkxqv.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4eG10cHR2eGtncGVxbXdreHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTAzMzAsImV4cCI6MjA2OTcyNjMzMH0.fMbDFewWtjYwY2OKdhMJj2JzmS1AV_ppMwIXACdZ300';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});