// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://bxxmtptvxkgpeqmwkxqv.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4eG10cHR2eGtncGVxbXdreHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTAzMzAsImV4cCI6MjA2OTcyNjMzMH0.fMbDFewWtjYwY2OKdhMJj2JzmS1AV_ppMwIXACdZ300';

// A custom storage implementation using cookies
const cookieStorage = {
  getItem: (key) => {
    const match = document.cookie.match(new RegExp('(^| )' + key + '=([^;]+)'));
    if (match) {
      return decodeURIComponent(match[2]);
    }
    return null;
  },
  setItem: (key, value) => {
    document.cookie = `${key}=${encodeURIComponent(value)};path=/;max-age=31536000;SameSite=Lax;secure`;
  },
  removeItem: (key) => {
    document.cookie = `${key}=;path=/;max-age=0;SameSite=Lax;secure`;
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: cookieStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
